openapi: 3.0.1
info:
  title: best-reddits
  description: Keep track of your favorite sub-reddits
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: Users
  description: User related endpoints
- name: Specification
  description: The swagger API specification
paths:
  /users:
    get:
      tags:
      - Users
      description: Fetch all users
      responses:
        200:
          description: Returns all users
          content: {}
    post:
      tags:
      - Users
      description: Create a new user
      requestBody:
        description: a user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserBody'
        required: true
      responses:
        200:
          description: Returns all users
          content: {}
  /users/{id}:
    get:
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: The id of the user to retrieve
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Return the user with the specified id
          content: {}
        404:
          description: User not found
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    UserBody:
      title: user
      required:
      - name
      type: object
      properties:
        name:
          type: string
          example: Amy
