openapi: 3.0.1
info:
  title: best-reddits
  description: Keep track of your favorite sub-reddits
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: Users
  description: User related endpoints
- name: Favorites
  description: Favorite related endpoints
- name: Specification
  description: The swagger API specification
paths:
  /users:
    get:
      tags:
      - Users
      description: Fetch all users
      responses:
        200:
          description: Returns all users
          content: {}
    post:
      tags:
      - Users
      description: Create a new user
      requestBody:
        description: a user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserBody'
        required: true
      responses:
        200:
          description: Returns all users
          content: {}
  /users/{id}:
    get:
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: The id of the user to retrieve
        required: true
        schema:
          type: string
      responses:
        200:
          description: Return the user with the specified id
          content: {}
        404:
          description: User not found
          content: {}
    put:
      tags:
      - Users
      requestBody:
        description: a user's properties
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserBody'
        required: true
      parameters:
      - name: id
        in: path
        description: The id of the user to retrieve
        required: true
        schema:
          type: string
      responses:
        200:
          description: Return the user with the specified id
          content: {}
        404:
          description: User not found
          content: {}
  /favorites:
    post:
      tags:
      - Favorites
      description: Create a favorite for a user
      requestBody:
        description: a favorite
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FavoriteBody'
        required: true
      responses:
        200:
          description: OK
  /favorites/{id}:
    get:
      tags:
      - Favorites
      parameters:
      - name: id
        in: path
        description: The id of the favorite to retrieve
        required: true
        schema:
          type: string
      responses:
        200:
          description: Return the favorite with the specified id
          content: {}
        404:
          description: Favorite not found
          content: {}
    delete:
      tags:
      - Favorites
      parameters:
      - name: id
        in: path
        description: The id of the favorite to delete
        required: true
        schema:
          type: string
      responses:
        204:
          description: The favorite was deleted
          content: {}
        404:
          description: Favorite not found
          content: {}
  /users/{id}/favorites:
    get:
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: The id of the user to retrieve
        required: true
        schema:
          type: string
      responses:
        200:
          description: Return the favorites for the user with the specified id
          content: {}
        404:
          description: User not found
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    UserBody:
      title: user
      required:
      - name
      type: object
      properties:
        name:
          type: string
          example: Amy
    UpdateUserBody:
      title: user
      type: object
      properties:
        name:
          type: string
          example: Amy
        alert:
          type: number
          example: 8
        notify:
          type: boolean
          example: true
    FavoriteBody:
      title: favorite
      required:
      - link
      - user_id
      type: object
      properties:
        link:
          type: string
          example: https://www.reddit.com/r/hognosesnakes/
        user_id:
          type: string
          example: 43da97e3-b219-4215-b31c-16171c413b49
